import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${notoSans.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <main className="mx-auto max-w-3xl">{children}</main>
      </body>
    </html>
  );
}
